# Generated by Django 5.0.2 on 2024-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genero', models.CharField(max_length=100)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('celContacto', models.IntegerField()),
                ('emailContacto', models.EmailField(max_length=254)),
            ],
        ),
    ]
